# Generated by Django 5.0.6 on 2024-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_time',
            field=models.DateField(),
        ),
    ]
