# Generated by Django 5.0.6 on 2024-06-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tour_end_time_alter_tour_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='all_seats',
            new_name='seats',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='remaining_seats',
        ),
    ]
