# Generated by Django 5.0.6 on 2024-06-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_all_seats_seat_seats_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tour_image',
            new_name='TourImage',
        ),
        migrations.RenameModel(
            old_name='Seat',
            new_name='TourSeat',
        ),
        migrations.RenameModel(
            old_name='Tour_service',
            new_name='TourService',
        ),
        migrations.RenameModel(
            old_name='Tour_video',
            new_name='TourVideo',
        ),
    ]
