# Generated by Django 5.0.6 on 2024-06-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_tour_image_tourimage_rename_seat_tourseat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourimage',
            old_name='path',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='tourservice',
            old_name='description',
            new_name='service_description',
        ),
        migrations.RenameField(
            model_name='tourvideo',
            old_name='path',
            new_name='media',
        ),
    ]
