# Generated by Django 5.0.6 on 2024-06-20 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_path_tourimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='author_avatas/'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
        migrations.AlterField(
            model_name='tourvideo',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='tour_videos/'),
        ),
    ]
