# Generated by Django 5.0.6 on 2024-06-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_tour_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TourSeat',
        ),
    ]
