# Generated by Django 5.0.6 on 2024-06-27 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_booking_created_at_alter_booking_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
