# Generated by Django 5.0.6 on 2024-06-28 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_booking_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_feedbag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('feedbag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.feedbag')),
            ],
            options={
                'verbose_name': 'Izoxga javob',
                'verbose_name_plural': 'Izohga javoblar',
            },
        ),
    ]
