# Generated by Django 5.0.6 on 2024-06-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_answer_feedbag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer_feedbag',
            new_name='AnswerFeedbag',
        ),
    ]
