# Generated by Django 5.0.6 on 2024-06-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_answer_feedbag_answerfeedbag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerfeedbag',
            old_name='description',
            new_name='answer',
        ),
    ]
