# Generated by Django 5.0.6 on 2024-06-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_description_answerfeedbag_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbag',
            old_name='description',
            new_name='feedbag',
        ),
    ]
